### ISSUE TITLE
wails dev returns error 

### ISSUE THREAD

**Issue by jtfogarty** [h8gi/wails-sveltekit#2]
Below is the output of `wails dev`

```
wails dev
Wails CLI v2.2.0

Executing: go mod tidy
  - Generating bindings: Done.
  - Installing frontend dependencies: Done.
  - Compiling frontend:     
    > wsk-01@0.0.0 build /home/j007ba7/project/wsk-01/frontend
    > vite build
    
     ELIFECYCLE  Command failed with exit code 1.
    
    error during build:
    Error: The filesystem router API has changed, see https://github.com/sveltejs/kit/discussions/5774 for details
        at create_routes_and_nodes (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:268:11)
        at create_manifest_data (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:25:28)
        at create (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/sync/sync.js:44:24)
        at Module.all (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/sync/sync.js:77:15)
        at config (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/exports/vite/index.js:211:33)
        at async runConfigHook (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62870:25)
        at async resolveConfig (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:62379:14)
        at async doBuild (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45248:20)
        at async build (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45237:16)
        at async CAC.<anonymous> (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/cli.js:756:9)
    


ERROR: exit status 1

```
#### wails doctor

```
~/project/wsk-01$ wails doctor
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Debian GNU/Linux
Version:        11
ID:             debian
Go Version:     go1.19.3
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.2.0
Package Manager:        apt

Dependency      Package Name            Status          Version
----------      ------------            ------          -------
*docker         docker.io               Available       20.10.5+dfsg1-1+deb11u2
gcc             build-essential         Installed       12.9
libgtk-3        libgtk-3-dev            Installed       3.24.24-4+deb11u2
libwebkit       libwebkit2gtk-4.0-dev   Installed       2.38.2-1~deb11u1
npm             npm                     Installed       8.19.2
*nsis           nsis                    Available       3.06.1-1
pkg-config      pkg-config              Installed       0.29.2

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - docker: sudo apt install docker.io
  - nsis: sudo apt install nsis
```

I attempt to fix with npx command
```
~/project/wsk-01$ npx svelte-migrate routes
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/j007ba7/.npm/_logs/2022-11-25T23_30_24_545Z-debug.log
Install for [ 'svelte-migrate@latest' ] failed with code 1
```
Node versions
```
~/project/wsk-01$ nodejs --version
v12.22.12
~/project/wsk-01$ npm --version
8.19.2
~/project/wsk-01$ npx --version
10.2.2
```
Any ideas on this is greatly appreciated

**Comment by jtfogarty** [comment]
This was a mismatch between npx and nodejs/npm
