### ISSUE TITLE
Does not work with the latest sveltkit

### ISSUE THREAD

**Issue by jtfogarty** [h8gi/wails-sveltekit#3]
The error I'm seeing is;

```
Error: ssr has been removed, set it in the appropriate +layout.js instead. See the PR for more information: https://github.com/sveltejs/kit/pull/6197
        at resolve (file:///home/j007ba7/project/wsk-01/frontend/.svelte-kit/output/server/index.js:2969:17)
        at resolve (file:///home/j007ba7/project/wsk-01/frontend/.svelte-kit/output/server/index.js:2905:34)
        at Object.handle (file:///home/j007ba7/project/wsk-01/frontend/.svelte-kit/output/server/chunks/hooks.server.js:2:26)
        at respond (file:///home/j007ba7/project/wsk-01/frontend/.svelte-kit/output/server/index.js:2903:42)
        at async visit (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:196:20)
    Error: ssr has been removed, set it in the appropriate +layout.js instead. See the PR for more information: https://github.com/sveltejs/kit/pull/6197
        at resolve (file:///home/j007ba7/project/wsk-01/frontend/.svelte-kit/output/server/index.js:2969:17)
        at resolve (file:///home/j007ba7/project/wsk-01/frontend/.svelte-kit/output/server/index.js:2905:34)
        at Object.handle (file:///home/j007ba7/project/wsk-01/frontend/.svelte-kit/output/server/chunks/hooks.server.js:2:26)
        at respond (file:///home/j007ba7/project/wsk-01/frontend/.svelte-kit/output/server/index.js:2903:42)
        at async visit (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:196:20)
    file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:30
                                throw new Error(format(details));
                                      ^ 
    Error: 500 /
        at file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:30:11
        at save (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:355:4)
        at visit (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:205:3)
    
    Node.js v18.12.1
    [vite-plugin-svelte-kit] Prerendering failed with code 1
    error during build:
    Error: Prerendering failed with code 1
        at ChildProcess.<anonymous> (file:///home/j007ba7/project/wsk-01/frontend/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.561_svelte@3.53.1+vite@3.2.4/node_modules/@sveltejs/kit/src/exports/vite/index.js:462:15)
        at ChildProcess.emit (node:events:513:28)
        at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

Any ideas?

**Comment by jtfogarty** [comment]
My system details are in #2
